#!/bin/bash

# Define the directory and filename
IMGDIR=$(xdg-user-dir PICTURES)
DATE=$(date +%Y-%m-%d_%H-%M-%S)
FILENAME="SCR_$DATE.png"
FILEPATH="$IMGDIR/$FILENAME"

# Capture the screenshot
gnome-screenshot -a -f $FILEPATH

# Upload the file using curl
RESPONSE=$(curl -s -F "file=@$FILEPATH" "https://kappa.lol/api/upload")

# Extract the links from the response
LINK=$(echo "$RESPONSE" | jq -r '.link')
DELLINK=$(echo "$RESPONSE" | jq -r '.delete')

# Copy the full link to the clipboard
echo $LINK | xclip -selection clipboard

# Notify the user
notify-send "quick-capture-sharing@Odyssey" "File: $FILEPATH\nUploaded to: $LINK\nDeletion: $DELLINK"

