#!/bin/bash

# Define the folder and filename
IMGDIR=$(xdg-user-dir PICTURES)/Screenshots/$(date +%Y-%m)
DATE=$(date +%Y-%m-%d_%H-%M-%S)
FILENAME="SCR_$DATE.png"
FILEPATH="$IMGDIR/$FILENAME"

# Create subfolder for current year-month if it does not exist
mkdir -p $IMGDIR

# Capture the screenshot
gnome-screenshot -a -f $FILEPATH

# Upload the file using curl
RESPONSE=$(curl -s -F "file=@$FILEPATH" "https://kappa.lol/api/upload")

# Extract the links from the response
LINK=$(echo "$RESPONSE" | jq -r '.link')
DELLINK=$(echo "$RESPONSE" | jq -r '.delete')

# Copy the full link to the clipboard
echo $LINK | xclip -selection clipboard

# Save information in the applet history file
echo -e "Folder: $IMGDIR\nFile: $FILENAME\nLink: $LINK\nDeletionLink: $DELLINK\n\n" >> ~/.quick-screenshot-sharing.history

# Notify the user
notify-send "quick-capture-sharing@Odyssey" "Folder: $IMGDIR\nFile: $FILENAME\nUploaded to: $LINK\nDeletion: $DELLINK"

